### ISSUE TITLE
window on windows too small and no fullscreen

### ISSUE THREAD

**Issue by HansHammel** [samueleaton/npm-scripts-gui#7]
on Windows, the window is only resizable to about +10% and the fullscreen button doesn't work (window stays same size and gets positioned at the upper left). Seems like the window has a fixed maximum size defined!?

Thx, great tool. 

btw is it possible to release a nw and/or standalone (browser) version?

**Comment by samueleaton** [comment]
This is not a windows bug. The app is designed to stay small. Fixing the window width made coding the CSS easier. I will look into allowing to resize the width.

**Comment by samueleaton** [comment]
I don't really see the point of making a NW app when its already made in electron. And the app works with processes in your kernel so it wouldn't be able to run in the browser.

**Comment by samueleaton** [comment]
The newest version `0.0.22` now doesn't have any limits on max window size.
